### Authentication
POST http://127.0.0.1:8000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "user": {
    "email": "test1@test.com",
    "password": "test1"
  }
}

> {% client.global.set("auth_token", response.body.user.token); %}

### Registration
POST http://127.0.0.1:8000/api/users
Content-Type: application/json
Accept: application/json

{
  "user": {
    "username": "test2",
    "email": "test2@test.com",
    "password": "test2"
  }
}

### Logout
POST http://127.0.0.1:8000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Current User
GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### Update User
PUT http://127.0.0.1:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "user": {
    "email": "test1@test.com",
    "bio": "I like to skateboard test",
    "image": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}
